spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat,wall,log4j
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 10
      min-idle: 10
      max-active: 30
      test-on-borrow: true
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      web-stat-filter:
        exclusions: '*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*'
      stat-view-servlet:
        allow:
        login-username: admin
        login-password: admin
      connection-init-sqls:
      - SET NAMES utf8mb4

mybatis:
  configuration:
    map-underscore-to-camel-case: true

mapper:
  not-empty: true
  mappers: com.ingot.common.mybatis.MyMapper
  identity: MYSQL

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
